project := "ThreadsProject".
project_version := "1.0".
buildfile_version := "1.0".
url_to_src := "https://github.com/tinycthread/tinycthread/archive/6957fc8383d6c7db25b60b8c849b29caab1caaee.zip".

build main_build.
end build.

build clean_build.
 message("Cleaning Threads...").
 clean("build").
end build.

default main_build.